DiglettsCaveRoute11_Script:
	jp EnableAutoTextBoxDrawing

DiglettsCaveRoute11_TextPointers:
	dw DiglettsCaveEntranceRoute11Text1

DiglettsCaveEntranceRoute11Text1:
	text_far _DiglettsCaveEntRoute11Text1
	text_end
