UndergroundPathRoute5_Script:
	jp EnableAutoTextBoxDrawing

UndergroundPathRoute5_TextPointers:
	dw UndergroundPathEntranceRoute5Text1

UndergroundPathEntranceRoute5Text1:
	text_far _UndergroundPathEntranceRoute5Text1
	text_end
