UndergroundPathWestEast_Script:
	jp EnableAutoTextBoxDrawing

UndergroundPathWestEast_TextPointers:
	dw UndergroundPathWestEastText1

UndergroundPathWestEastText1:
	text_far _UndergroundPathWestEastText1
	text_end
